---
apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: enterprise-2.13.6-1
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjzCCATSgAwIBAgIRAPnQ5cdIShJyjjXyb8rVaJwwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwOTA3MTM0
          NzA3WhcNMzMwOTA0MTM0NzA3WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOgCT0ne+9hZV2YG
          9tpwSX84VZkNwI10sWqx8l5jS01rfObvBBKjOB0N1pghw7YQfYdhQy+iWY5VQsJh
          +tUxX8ijRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBSh2HpxhbK8vQI5CzquGfPAgd4k1jAKBggqhkjOPQQDAgNJADBGAiEA
          mWx9+GSYe/ieR+nzNHGJhAgN71c6itaiHmFD+I8io/UCIQC5ZLTK7sACEBS4R6u9
          cRBKMUUh4p6gTRqcU9wsD7NtPg==
          -----END CERTIFICATE-----
        imagePullSecrets:
        - name: buoyant-registry-secret
        identity:
          issuer:
            scheme: kubernetes.io/tls
        enablePodAntiAffinity: true
        # proxy configuration
        proxy:
          resources:
            cpu:
              request: 100m
            memory:
              limit: 250Mi
              request: 20Mi
        # controller configuration
        controllerReplicas: 3
        controllerResources: &controller_resources
          cpu: &controller_resources_cpu
            limit: ""
            request: 100m
          memory:
            limit: 250Mi
            request: 50Mi
        destinationResources: *controller_resources
        # identity configuration
        identityResources:
          cpu: *controller_resources_cpu
          memory:
            limit: 250Mi
            request: 10Mi
        # heartbeat configuration
        heartbeatResources: *controller_resources
        # proxy injector configuration
        proxyInjectorResources: *controller_resources
        webhookFailurePolicy: Fail
        # service profile validator configuration
        spValidatorResources: *controller_resources
