---
apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: enterprise-2.13.6-0
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjzCCATSgAwIBAgIRANiaDAGAWQKMZBpkJFMshDwwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwODEwMTIy
          MjMzWhcNMzMwODA3MTIyMjMzWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABN3xk6TZNI8HfQw/
          uUNRMkkqR+JxUO/Q0ofqSYrmYbUsUClRSJW5OQ07Cxaaei+x4uyEemMGj0nEa136
          bFznMCujRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBRWcRH0l6ny97owjNyrSY2i9pevtTAKBggqhkjOPQQDAgNJADBGAiEA
          +aaVm4BW3Taga9d8pmvzy56nGTH/osKS/Wf/W0DY5igCIQCNmXt/xBd+Hjj69y5m
          e4o0u2fBv62ohS4InJdYJHuMmg==
          -----END CERTIFICATE-----
        imagePullSecrets:
        - name: buoyant-registry-secret
        identity:
          issuer:
            scheme: kubernetes.io/tls
