---
apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: enterprise-2.13.6-0
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjjCCATSgAwIBAgIRAPay06Y8KfBjm+nyUyZWVGwwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwOTA3MTM0
          NzIwWhcNMzMwOTA0MTM0NzIwWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEu3vhCuJApOtgc8
          CBq/COqiH/nSjiFHkxmMj3iCq43lWqmr5iy1NqL/8KZwdOTCNWjWb3c37DOSI0ym
          GvTfY5WjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBTwsJE1sSES0I8OisaWj6W1Lq6IqzAKBggqhkjOPQQDAgNIADBFAiEA
          7Xp4pBPqK1E0orxG8U0DuSWhoopvWBlzXQ7W+xfTVLMCIC3swZI7X2hC72Ef27MK
          l3PdY6zjOESkeNv9jL0RB47I
          -----END CERTIFICATE-----
        imagePullSecrets:
        - name: buoyant-registry-secret
        identity:
          issuer:
            scheme: kubernetes.io/tls
