---
apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: enterprise-2.13.6-1
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjzCCATSgAwIBAgIRAMUEgYtDebAgfZmyUHJNrSMwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwOTA3MTM0
          NzMyWhcNMzMwOTA0MTM0NzMyWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIcUYA5Iz9DghXz4
          7YyAhH4lp4gimM/Jys7sVK4aIYW5+ZxHlJpoQG28JqQCpEP5NjvvXLKh2RQeeDrC
          0EI4O6+jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBRi61WDD54cCtf3nYxpzCkIg0z5qTAKBggqhkjOPQQDAgNJADBGAiEA
          1Yd1evQYEKNbMWGSOTxEhdTkEimiNg6qkJ0OnQqMmGYCIQD2RMs+r5KKkbr8cOxY
          Dtbmfn12MBKpiqSULTRNaE6LdA==
          -----END CERTIFICATE-----
        imagePullSecrets:
        - name: buoyant-registry-secret
        identity:
          issuer:
            scheme: kubernetes.io/tls